version: '3.5'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_PASSWORD=passwd
      - SERVER_SSL_ENABLED=false
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          memory: 26Gb

volumes:
  esdata:
    driver: local
networks:
  default:
    name: elastic
